source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'catest_Example', :exclusive => true do
  pod 'catest', :path => '../'
end

target 'catest_Tests', :exclusive => true do
#  pod 'catest', :path => '../'

#  pod 'Specta'
#  pod 'Expecta'
#  pod 'FBSnapshotTestCase'
#  pod 'Expecta+Snapshots'
end
